INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [9148] using StatReload
INFO:     Started server process [5816]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\_backends\_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\server.py", line 59, in get_puntos_bolsas
    cliente.download_with_custom_key()
  File "D:\CIRAL\VISION\ftp_ck\cliente.py", line 91, in download_with_custom_key
    subprocess.run(cmd, check=True)
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['scp', '-i', 'C:/Users/KINGDOM/ciral', 'LabCkCiral@172.19.69.246:/home/LabCkCiral/ftp_server/images/imgSend.jpg', 'D:\\CIRAL\\VISION\\ftp_images\\imgSend.jpg']' returned non-zero exit status 1.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\_backends\_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\server.py", line 59, in get_puntos_bolsas
    cliente.download_with_custom_key()
  File "D:\CIRAL\VISION\ftp_ck\cliente.py", line 91, in download_with_custom_key
    subprocess.run(cmd, check=True)
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['scp', '-i', 'C:/Users/KINGDOM/ciral', 'LabCkCiral@172.19.69.246:/home/LabCkCiral/ftp_server/images/imgSend.jpg', 'D:\\CIRAL\\VISION\\ftp_images\\imgSend.jpg']' returned non-zero exit status 1.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\_backends\_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\server.py", line 59, in get_puntos_bolsas
    cliente.download_with_custom_key()
  File "D:\CIRAL\VISION\ftp_ck\cliente.py", line 91, in download_with_custom_key
    subprocess.run(cmd, check=True)
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['scp', '-i', 'C:/Users/KINGDOM/ciral', 'LabCkCiral@172.19.69.246:/home/LabCkCiral/ftp_server/images/imgSend.jpg', 'D:\\CIRAL\\VISION\\ftp_images\\imgSend.jpg']' returned non-zero exit status 1.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [5816]
INFO:     Stopping reloader process [9148]
INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12948] using StatReload
INFO:     Started server process [10928]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'server.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [10928]
INFO:     Started server process [3608]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'server.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [3608]
INFO:     Started server process [3864]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [3864]
INFO:     Stopping reloader process [12948]
INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12132] using StatReload
INFO:     Started server process [3592]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'list_type', 'loc': ('response',), 'msg': 'Input should be a valid list', 'input': None}

INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [3592]
INFO:     Stopping reloader process [12132]
C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\CIRAL\\VISION\\ftp_ck\\python': [Errno 2] No such file or directory
C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\CIRAL\\VISION\\ftp_ck\\python': [Errno 2] No such file or directory
C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\CIRAL\\VISION\\ftp_ck\\python': [Errno 2] No such file or directory
C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\CIRAL\\VISION\\ftp_ck\\python': [Errno 2] No such file or directory
C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\CIRAL\\VISION\\ftp_ck\\python': [Errno 2] No such file or directory
INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [6788] using StatReload
INFO:     Started server process [2324]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'server.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2324]
INFO:     Started server process [8396]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [8396]
INFO:     Stopping reloader process [6788]
INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [2952] using StatReload
INFO:     Started server process [2680]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'cliente.py'. Reloading...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'list_type', 'loc': ('response',), 'msg': 'Input should be a valid list', 'input': None}

INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2680]
WARNING:  StatReload detected changes in 'cliente.py'. Reloading...
INFO:     Started server process [13164]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Traceback (most recent call last):
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

INFO:     Started server process [8196]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [8196]
INFO:     Stopping reloader process [2952]
INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [3828] using StatReload
INFO:     Started server process [3888]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'cliente.py'. Reloading...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'list_type', 'loc': ('response',), 'msg': 'Input should be a valid list', 'input': None}

INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [3888]
INFO:     Started server process [11124]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'cliente.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [11124]
WARNING:  StatReload detected changes in 'cliente.py'. Reloading...
INFO:     Started server process [12764]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Traceback (most recent call last):
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KINGDOM\AppData\Local\Programs\Python\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

INFO:     Started server process [6768]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6768]
INFO:     Stopping reloader process [3828]
INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12160] using StatReload
INFO:     Started server process [11576]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'cliente.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for connections to close. (CTRL+C to force quit)
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [11576]
INFO:     Started server process [1668]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1668]
INFO:     Stopping reloader process [12160]
INFO:     Will watch for changes in these directories: ['D:\\CIRAL\\VISION\\ftp_ck']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [256] using StatReload
INFO:     Started server process [5936]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Warning: Permanently added '172.19.69.246' (ED25519) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:/Users/KINGDOM/ciral' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "C:/Users/KINGDOM/ciral": bad permissions
WARNING:  StatReload detected changes in 'cliente.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for background tasks to complete. (CTRL+C to force quit)
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [5936]
INFO:     Started server process [9008]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Warning: Permanently added '172.19.69.246' (ED25519) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:/Users/KINGDOM/ciral' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "C:/Users/KINGDOM/ciral": bad permissions
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CIRAL\VISION\ftp_ck\ckcuda\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'list_type', 'loc': ('response',), 'msg': 'Input should be a valid list', 'input': None}

INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [9008]
INFO:     Stopping reloader process [256]
